apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: express-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
